"""N11 — Correlation & Triage. Generated by Konnaxion Mega Diagnostic Pack."""
from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from diagcore.config import AppConfig, load_config
from profiles.levelup.konnaxion_diag.checks import run_domain

LEVEL_ID = "N11"
LEVEL_NAME = "Correlation & Triage"
PURPOSE = "Correlate current-session evidence and identify the likely failing domain."

def run(config: AppConfig | None = None):
    cfg = load_config() if config is None else config
    return run_domain(cfg, LEVEL_ID, LEVEL_NAME)

if __name__ == "__main__":
    from diagcore.verdicts import exit_code
    raise SystemExit(exit_code(run().verdict))
